services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DB_DSN: postgresql+asyncpg://notora:notora@tests_db:5432/notora
    depends_on:
      tests_db:
        condition: service_healthy

  tests_db:
    image: postgres:16
    environment:
      POSTGRES_USER: notora
      POSTGRES_PASSWORD: notora
      POSTGRES_DB: notora
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notora -d notora"]
      interval: 5s
      timeout: 2s
      retries: 5
